language: go
go:
    - 1.6
    - 1.7

services:
  - postgresql

addons:
  postgresql: "9.5"

env:
  DB_ADDR: "localhost:5432"
  DB_USER: postgres
  DB_PASS: password
  DB_NAME: dbox_test

before_install: 
  - sleep 60
  - psql -c "create database dbox_test;" -U postgres
  - psql -c "alter user postgres password 'password';" -U postgres
  - go get github.com/stretchr/testify/assert
  - go get github.com/inpime/dbox

script:
  - make test