test:
	go test -v ./...
testx:
	go test -v -run=TestBoltDBSuperEncoderDecoder_basic ./...
testbench:
	go test -v -bench=. -benchmem -run=. -cpu=1,2 ./...
benchx:
	go test -v -bench=BenchmarkTestBoltDBStore_simpleStrategy -benchmem -cpu=1,2 ./...